#!/usr/bin/env python3
"""Refresh guide illustrations from the registry-selected assembly mesh.

The scene cameras are guide authoring, not CAD changes. Geometry and its source
hash are verified before rendering. --write updates existing authored images;
otherwise pictures and a receipt go only to the requested scratch directory.
"""
import argparse, copy, hashlib, importlib, json, os, re, shutil, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / 'hardware/build-guide/src'

SHELF_FASTENING_CENTERS = ((15.588457268119896,-9),(0,18),(-15.588457268119896,-9))

def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

def checked_source():
    sys.path.insert(0, str(ROOT / 'hardware/tools/rendering'))
    from source import checked_source as resolve, selected
    lock, registry = selected()
    if lock.get('scene_review_cad') != registry['main']:
        raise ValueError('Review scene dimensions against the selected CAD before rendering')
    return resolve((lock, registry))

def scenes():
    library = json.loads((ROOT / 'hardware/rendering/scenes/views.json').read_text())
    result = {}
    # The historical head-fastener scene was generated by a specialized section
    # routine. Its actual image contains no enclosure and is not a whole model.
    for scene in library.values():
        path = scene['output']; view = scene['view']; selected = view.get('select', ['all'])
        if path in ('assets/r18/head-fastener-cutaway.png','assets/r16/service-stand.png') or not (SRC / path).exists():
            continue
        if any((part in selected or 'all' in selected) and part not in view.get('exclude', []) for part in ('P08', 'P14', 'P35', 'P36', 'FB32', 'FB01', 'FB24', 'FB41', 'E01', 'E06', 'E07', 'E08', 'E09', 'E14', 'E16', 'E17', 'E18')) or view.get('hardware') or path in ('assets/r16/base-cover-joints.png','assets/r16/base-pi-joints.png','assets/r16/base-shifter-joints.png'):
            result[path] = copy.deepcopy(scene)
    community = {
        'vent-locations': dict(select=['FB01','FB03','FB41'],camera=[.7,.8,-1.6],title='Front and rear vents'),
        'audio-cradle-fasteners': copy.deepcopy(library['r16/base-audio-joints']['view']),
        'base-board-nut-locations': dict(select=['FB01'],camera=[.12,.3,-1.8],title='Eight M2 board nuts — four Pi, two per signal board',feature_labels=[{'text':f'P{i+1}','point':[x,y,-17]} for i,(x,y) in enumerate([(-74.5,2.5),(-25.5,2.5),(-74.5,60.5),(-25.5,60.5)])]+[{'text':name,'point':[-18,y,-15]} for name,y in [('S1a',-22.08),('S1b',-11.92),('S2a',-44.08),('S2b',-33.92)]]),
    }
    for name, view in community.items():
        view['labels_by_root'] = copy.deepcopy(library['r16/base-speakers']['view']['labels_by_root'])
        view['title'] = {'audio-cradle-fasteners':'Audio cradle — fit all three screws before the module'}.get(name, view.get('title'))
        result[f'assets/community/{name}.png'] = dict(view=view,thumbnail=False)
    # The presentation front view is captured in Fusion, not this renderer.
    # Its settings and source are recorded in rendering/presentation-front.json.
    result['assets/part-P35.png'] = dict(view=dict(select=['P35'],camera=[.9,-1.6,.9],clean=True),thumbnail=True)
    result['assets/r16/step-29.png'] = dict(view=dict(select=['P35','P36','P37','P38','P39','P40'],camera=[.9,1.6,.9],offset={'P37':[0,0,-12],'P38':[0,0,10],'P39':[0,0,10],'P40':[0,9,0]},title='Test-fit the backpack details',footer='Fit the tanks first; arrows show the parts coming together'),thumbnail=False)
    for path, scene in result.items():
        v = scene['view']
        v['title'] = re.sub(r'^R\d+\s*/\s*', '', v.get('title','Assembly')).replace('CURRENT ASSEMBLY','Assembly').replace('COMPLETE CURRENT ASSEMBLY','Complete robot')
        v['title'] = v['title'].replace('BODY','FRAME') if path.endswith('base-nuts.png') else v['title']
        v['footer'] = 'Base drawn lighter so its inside is visible' if 'FB01' in v.get('select',[]) else ''
        if path.endswith('front-grille-detail.png'):
            v['title']='Front microphone grille — four M3 × 6 screws'
            v['footer']='88 × 40.8 × 2 mm • no washers'
        if path.endswith('audio-cradle-fasteners.png'):
            v['footer']='Use the fitted base nuts • the middle screw goes in before the module'
        if path.endswith('wago-pockets.png'):
            v['footer']='Tape goes between each flat face and its connector • no printed clamps'
        if path.endswith('base-inlet.png'):
            v['select']=['FB21','E18'];v['title']='Power jack and removable plate';v['footer']='Keep enough wire slack to remove the plate'
        if path.endswith('base-board-nut-locations.png'):
            v['footer']='P1–P4: Pi • S1a/S1b: rear signal board • S2a/S2b: front signal board'
    result['assets/r21/base-cover.png']['view'].update(clean=True)
    result['assets/r16/base-button.png']['view']['footer']='Four insulated button leads'
    result['assets/r21/base-frame.png']['view'].update(occ={'P01':[0],'P02':[0,1]}, title='Lower collar and both uprights', clean=True)
    return result

def front_diagrams(render, output):
    """Real CAD sections and nominal screw/nut solids; no placeholder blocks."""
    import numpy as np
    import trimesh
    from PIL import Image, ImageDraw, ImageFont
    def clip(mesh, normal, origin):
        vertices, faces, _ = trimesh.intersections.slice_faces_plane(mesh.vertices, mesh.faces, normal, origin)
        return trimesh.Trimesh(vertices, faces, process=False)
    original = render.meshes
    chosen = [m for m in original if m['id'] in ('FB01','FB41')]
    # A narrow CAD slice through the robot-right lower front fastening position.
    # Cut surfaces are left open deliberately; original surviving triangles remain.
    local = []
    for m in chosen:
        mesh = trimesh.Trimesh(m['v'],m['f'],process=False)
        for normal, origin in [([1,0,0],[-33,0,0]),([-1,0,0],[-21,0,0]),([0,-1,0],[0,-83,0]),([0,0,1],[0,0,-49]),([0,0,-1],[0,0,-32])]:
            mesh = clip(mesh,normal,origin)
        item = dict(m,v=mesh.vertices,f=mesh.faces,flat_shading=True)
        item.pop('normals',None); item.pop('corner_normals',None)
        local.append(item)
    from guide_fasteners import screw as fastener_screw, hex_nut
    def nut(position):
        return hex_nut(3, position, [0,1,0])
    render.colors.update({'M3 screw':(177,186,197),'M3 nut':(177,186,197)})
    def panel(name, parts, title, footer, camera):
        render.meshes=parts
        render.render(name,dict(select=['all'],camera=camera,title=title,footer=footer,clean=True,size=[900,850],margin=65))
    # Nominal nut midplane y=-90.6, seat centre z=-40.5; the insertion lift is +Z.
    panel('front-nut-low',[local[0],nut(np.array([-27,-90.6,-46.5]))],'','',[.8,1,-.15])
    panel('front-nut-seated',[local[0],nut(np.array([-27,-90.6,-40.5]))],'','',[.8,1,-.15])
    # Installed screw: head underside at panel front y=-95; 6 mm shank ends -89.
    installed=[*local,nut(np.array([-27,-90.6,-40.5]))]+fastener_screw(3,6,[-27,-95,-40.5],[0,1,0])
    # Exact planar intersections avoid showing open mesh cuts as solid material.
    # Every colored outline comes from the actual CAD/nominal hardware triangles.
    section_image=Image.new('RGB',(900,850),(243,247,250))
    sd=ImageDraw.Draw(section_image)
    def xy(v):return (90+(v[1]+99)*38,680-(v[2]+48)*38)
    for m in installed:
        mesh=trimesh.Trimesh(m['v'],m['f'],process=False)
        segments=trimesh.intersections.mesh_plane(mesh,[1,0,0],[-27,0,0])
        color={'FB01':(88,107,121),'FB41':(166,91,53)}.get(m['id'],(80,92,107))
        for seg in segments:sd.line([xy(seg[0]),xy(seg[1])],fill=color,width=5)
    f=ImageFont.truetype(os.environ['BGB_RENDER_FONT'],48)
    # Leader positions refer to the actual stack planes at this bore.
    for label,location,end in [('Screw head',[-27,-96.5,-40.5],(28,695)),('2 mm grille',[-27,-94,-44],(315,785)),('Enclosure seat',[-27,-92.5,-38.5],(410,65)),('M3 nut',[-27,-90.6,-42.5],(630,665))]:
        point=xy(location);sd.line([point,end],fill=(75,85,96),width=2);sd.text(end,label,font=f,fill=(34,56,78))
    section_image.save(output/'front-fastening-section.png',optimize=True)
    render.meshes=original
    fontpath=os.environ['BGB_RENDER_FONT']
    def compose(name, pictures, labels):
        # No drawn title or instructions: the guide caption gives the view.
        canvas=Image.new('RGB',(900,1020*len(pictures)),(243,247,250));d=ImageDraw.Draw(canvas)
        for i,pic in enumerate(pictures):
            y=1020*i
            canvas.paste(Image.open(output/(pic+'.png')),(0,y))
            d.multiline_text((28,y+855),labels[i],font=ImageFont.truetype(fontpath,48),fill=(34,56,78),spacing=10)
        if name == 'front-nut-entry.png':
            d.line([(770,615),(770,385)],fill=(166,91,53),width=8)
            d.polygon([(770,360),(751,399),(789,399)],fill=(166,91,53))
            d.text((722,302),'UP',font=ImageFont.truetype(fontpath,48),fill=(34,56,78))
            d.text((700,640),'6 mm',font=ImageFont.truetype(fontpath,48),fill=(34,56,78))
        canvas.save(output/name,optimize=True)
    compose('front-nut-entry.png',['front-nut-low','front-nut-seated'],['M3 nut, 6 mm below the seat','Seated'])
    compose('front-grille-fastening.png',['front-fastening-section'],['M3 × 6 · no washer'])
    return ['assets/community/front-nut-entry.png','assets/community/front-grille-fastening.png']

def verify_stand_reuse(provenance, registry, accepted, rows):
    """Keep the original export identity; allow reuse only with unchanged fixtures."""
    if provenance['cad']['cloud_file_id'] != registry['main']['cloud_file_id']:
        raise ValueError('Stand belongs to another CAD lineage')
    original_manifest = ROOT/provenance['cad']['release_manifest']
    if digest(original_manifest) != provenance['cad']['release_manifest_sha256']:
        raise ValueError('Stand original release manifest changed')
    original = json.loads(original_manifest.read_text())
    if not any(r['path'] == provenance['native_source']['path'] and r['sha256'] == provenance['native_source']['sha256'] for r in original['artifacts']):
        raise ValueError('Stand native source is not bound by its original release')
    evidence = {r['path']:r for r in provenance['occurrences']}
    if len(rows) != 8 or set(evidence) != {r['path'] for r in rows}:
        raise ValueError('Expected all eight original stand occurrences')
    for row in rows:
        occurrence = accepted[row['path']]
        if row['transform'] != occurrence['transform'] or len(occurrence['bodies']) != 1 or abs(row['volume_cm3']-occurrence['bodies'][0]['volume'])>1e-8:
            raise ValueError('Stand occurrence differs from accepted snapshot: '+row['path'])
        # This particular exported fixture uses identity occurrence transforms;
        # compare the native bounding box as an additional independent check.
        if row['transform'] != [1.,0.,0.,0.,0.,1.,0.,0.,0.,0.,1.,0.,0.,0.,0.,1.]:
            raise ValueError('Stand reuse requires reviewing a changed coordinate frame')
        actual_bounds = occurrence['bodies'][0]['bounds']
        old_bounds = evidence[row['path']]['world_bounds_mm']
        if any(abs(actual_bounds[i][j]*10-old_bounds[i][j])>0.01 for i in range(2) for j in range(3)):
            raise ValueError('Stand native bounds changed: '+row['path'])

def nut_axis_transform(axis):
    """Keep nut flats parallel to the accepted pockets' X-facing flats.

    An unconstrained axis alignment can also roll the hexagon, putting its
    corners against the pocket walls. Both accepted pocket axes retain X.
    """
    if list(axis) == [0, 0, 1]:
        return [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]
    if list(axis) == [0, 1, 0]:
        return [[1,0,0,0],[0,0,1,0],[0,-1,0,0],[0,0,0,1]]
    raise ValueError('Review hex-pocket orientation for this nut axis')


def base_nut_diagrams(render, output):
    """Show accepted pocket surfaces and nominal nuts along their insertion axes.

    Coordinates are assembly millimetres, reviewed against R27's unchanged board/
    cover recesses and revised rear slots. Mesh clipping exposes each real feature,
    not a substitute shape. Glue is not drawn as a qualified bond geometry.
    """
    import numpy as np
    import trimesh
    from PIL import Image, ImageDraw, ImageFont
    original = render.meshes
    shell = next(m for m in original if m['id'] == 'FB01')
    def crop(bounds):
        mesh = trimesh.Trimesh(shell['v'], shell['f'], process=False)
        for axis in range(3):
            for side, sign in ((0, 1), (1, -1)):
                normal = np.zeros(3); normal[axis] = sign
                origin = np.zeros(3); origin[axis] = bounds[side][axis]
                vertices, faces, _ = trimesh.intersections.slice_faces_plane(mesh.vertices, mesh.faces, normal, origin)
                mesh = trimesh.Trimesh(vertices, faces, process=False)
        return dict(id='FB01',occ=0,root='FB01 pocket section',v=mesh.vertices,f=mesh.faces,source={},flat_shading=True)
    def nut(af, thickness, bore, position, axis):
        from guide_fasteners import hex_nut
        return hex_nut(int(bore),position,axis,af=af,thickness=thickness,bore=bore)
    specs=[
        ('board',4.,1.6,2.,[-25.5,2.5,-16.], [0,0,1], [[-32,-4.5,-18.2],[-19,9.5,-5.8]],[-.46,-.59,-1.], 'Board nuts — M2, eight places', 'Enter from the open bottom; glue in the recess before fitting the board'),
        ('cover',5.5,2.4,3.,[99,68,-60.6], [0,0,1], [[89,56,-66],[107,80,-48]],[-.69,-.67,-1.], 'Bottom-cover nuts — M3, four places', 'Enter from the open bottom; glue in the recess before fitting the cover'),
        ('rear',5.5,2.4,3.,[-26,85.1,-49.5], [0,1,0], [[-37,78,-60.5],[-15,96,-38.5]],[.44,-1.,-.61], 'Rear-grille nuts — M3, four places', 'Tilt the enclosure; load from inside toward the rear grille'),
    ]
    outputs=[]
    fontpath=os.environ['BGB_RENDER_FONT']
    for name,af,thickness,bore,position,axis,bounds,camera,title,footer in specs:
        section=crop(bounds)
        # Identical framing in all three panels makes the loading direction clear.
        framing=[np.minimum(bounds[0], np.array(position)-np.array(axis)*9-4).tolist(),np.maximum(bounds[1],np.array(position)+4).tolist()]
        for state,offset in [('empty',None),('enter',-7),('seated',0)]:
            render.meshes=[section]
            if offset is not None:render.meshes.append(nut(af,thickness,bore,np.array(position)+np.array(axis)*offset,axis))
            render.render(f'base-{name}-{state}',dict(select=['all'],camera=camera,clean=True,size=[700,650],margin=65,frame_world_bounds=framing))
        # Use a shared crop and scale for both states; preserve orientation and
        # apparent size instead of stacking two mostly empty full-size canvases.
        states=[Image.open(output/f'base-{name}-{state}.png').convert('RGB')
                for state in ('enter','seated')]
        boxes=[]
        for image in states:
            pixels=np.array(image).astype(int)
            bg=pixels[0,0]
            yy,xx=np.where(np.max(np.abs(pixels-bg),axis=2)>18)
            boxes.append((xx.min(),yy.min(),xx.max()+1,yy.max()+1))
        cropbox=(max(0,min(b[0] for b in boxes)-14),max(0,min(b[1] for b in boxes)-14),
                 min(700,max(b[2] for b in boxes)+14),min(650,max(b[3] for b in boxes)+14))
        canvas=Image.new('RGB',(700,480),(243,247,250));draw=ImageDraw.Draw(canvas)
        short_title={'board':'8 × M2 nuts','cover':'4 × M3 nuts','rear':'4 × M3 nuts'}[name]
        draw.text((24,18),short_title,font=ImageFont.truetype(fontpath,38),fill=(34,56,78))
        for i,image in enumerate(states):
            image=image.crop(cropbox)
            image.thumbnail((314,338),Image.Resampling.LANCZOS)
            canvas.paste(image,(18+i*350+(314-image.width)//2,84+(338-image.height)//2))
        draw.line((319,247,377,247),fill=(169,85,34),width=5)
        draw.polygon([(377,247),(362,238),(362,256)],fill=(169,85,34))
        small=ImageFont.truetype(fontpath,32)
        draw.text((28,430),'Flats aligned',font=small,fill=(34,56,78))
        draw.text((378,430),'Seated flat',font=small,fill=(34,56,78))
        path=f'assets/community/base-{name}-nut-entry.png';canvas.save(output/Path(path).name,optimize=True);outputs.append(path)
    render.meshes=original
    return outputs

def verify_reference_identities(meshes):
    """Fresh exports may omit part_id; never silently drop accepted references."""
    expected = {'FBREF Fuse F2:1': 'E07',
                'FBREF Capacitor C1:1': 'E08', 'FBREF Capacitor C2:1': 'E08'}
    found = [m for m in meshes if m['root'].startswith(('FBREF Fuse F', 'FBREF Capacitor C'))]
    if len(found) != len(expected) or {m['root']: m['id'] for m in found} != expected:
        raise ValueError('Missing or incorrect fuse/capacitor render identities')


def action_diagrams(render, output):
    """Single-action CAD views with nominal fasteners and readable SVG captions.

    Printed surfaces are clipped or translated accepted triangles. Purchased-part
    envelopes are omitted; the WAGO inset is recognizable orientation artwork,
    not a substitute dimensioned CAD model. Metal fasteners use nominal sizes with visible threads and recessed drives.
    """
    import base64
    import html
    import itertools
    import numpy as np
    import trimesh
    original = render.meshes
    render.colors.update({'M3 screw':(177,186,197),'M3 nut':(177,186,197)})
    outputs = []
    font = 'Arial, sans-serif'
    ink = '#22384e'
    def chosen(ids, occurrences=None):
        return [dict(m) for m in original if m['id'] in ids and
                (not occurrences or m['id'] not in occurrences or m['occ'] in occurrences[m['id']])]
    def translated(parts, offsets):
        result=[]
        for m in parts:
            off=offsets.get(m['id'],[0,0,0]);item=dict(m,v=m['v']+np.array(off))
            item.pop('normals',None);item.pop('corner_normals',None);result.append(item)
        return result
    def cropped(parts, bounds):
        result=[]
        for m in parts:
            mesh=trimesh.Trimesh(m['v'],m['f'],process=False)
            for axis in range(3):
                for side,sign in ((0,1),(1,-1)):
                    normal=np.zeros(3);normal[axis]=sign
                    origin=np.zeros(3);origin[axis]=bounds[side][axis]
                    v,f,_=trimesh.intersections.slice_faces_plane(mesh.vertices,mesh.faces,normal,origin)
                    mesh=trimesh.Trimesh(v,f,process=False)
            if len(mesh.faces):result.append(dict(m,v=mesh.vertices,f=mesh.faces,flat_shading=True))
        return result
    def solid(mesh, pid, axis, position):
        mesh.apply_transform(trimesh.geometry.align_vectors([0,0,1],axis));mesh.apply_translation(position)
        return dict(id=pid,occ=0,root=pid,v=mesh.vertices,f=mesh.faces,source={},flat_shading=True)
    def screw(d,length,seat,axis):
        from guide_fasteners import screw as modeled_screw
        return modeled_screw(d,length,seat,axis)
    def shelf_screw(seat):
        rows=screw(3,8,seat,[0,0,-1])
        # Owner-measured M3 head, R29 approval evidence; keep nominal threads.
        for row in rows[1:]:row['v']=(row['v']-seat)*[5.33/5.5,5.33/5.5,3.03/3]+seat
        return rows
    def nut(d,center,axis):
        from guide_fasteners import hex_nut
        return hex_nut(d,center,axis)
    def tube(points, radius, color_id='Cable'):
        parts=[]
        for a,b in zip(points,points[1:]):
            a=np.array(a,float);b=np.array(b,float);delta=b-a
            parts.append(solid(trimesh.creation.cylinder(radius,float(np.linalg.norm(delta)),sections=20),color_id,delta/np.linalg.norm(delta),(a+b)/2))
        return parts
    def round_horn(center):
        # Measured original disk OD; profile thickness is illustrative.
        n=80;v=[]
        for z in [-.8,.8]:
            for radius in [11.775,3.0]:
                for i in range(n):
                    angle=2*np.pi*i/n;v.append([radius*np.cos(angle),radius*np.sin(angle),z])
        faces=[]
        for i in range(n):
            j=(i+1)%n
            for a,b,c,d in [(i,j,2*n+j,2*n+i),(n+i,3*n+i,3*n+j,n+j),(i,n+i,n+j,j),(2*n+i,2*n+j,3*n+j,3*n+i)]:faces.extend([[a,b,c],[a,c,d]])
        return solid(trimesh.Trimesh(v,faces,process=False),'Horn outline',[0,0,1],center)
    def svg_text(x,y,value,size=21,anchor='start'):
        return f'<text x="{x}" y="{y}" font-size="{size}" text-anchor="{anchor}" fill="{ink}">{html.escape(value)}</text>'
    def emit(name,parts,camera,title,labels,marks=(),arrows=(),bounds=None,extra=''):
        if name == 'tank-ring-bond':
            from guide_closeups import pose_parts
            rotation=np.array([[1,0,0],[0,0,1],[0,-1,0]])
            parts=pose_parts(parts,rotation);camera=(rotation@camera).tolist()
            arrows=[(rotation@a,rotation@b) for a,b in arrows]
            marks=[(label,rotation@point) for label,point in marks]
        # One 420px-wide image per action remains readable in the mobile column.
        render.meshes=parts
        if bounds is None:
            points=np.concatenate([m['v'] for m in parts]);bounds=[points.min(0)-2,points.max(0)+2]
        view=dict(select=['all'],camera=camera,clean=True,size=[840,720],margin=65,frame_world_bounds=np.array(bounds).tolist())
        render.render('action-'+name,view)
        png=(output/('action-'+name+'.png')).read_bytes()
        z=np.array(camera,dtype=float);z/=np.linalg.norm(z);x=np.cross([0,0,1],z);x/=np.linalg.norm(x);y=np.cross(z,x);R=np.array([x,y,z]).T
        corners=np.array(list(itertools.product(*zip(*bounds))))@R
        low=corners[:,:2].min(0);high=corners[:,:2].max(0);span=high-low
        scale=min(710/max(span[0],1),590/max(span[1],1));center=(low+high)/2
        def project(p):
            p=np.array(p)@R
            return ((p[0]-center[0])*scale/2+210,420-(p[1]-center[1])*scale/2-180)
        # The title names the picture for screen readers only; the guide caption
        # gives the view and the actions give instructions. Labels name parts,
        # sizes and numbered marks, under the picture.
        body=f'<image x="0" y="60" width="420" height="360" href="data:image/png;base64,{base64.b64encode(png).decode()}"/>'
        for a,b in arrows:
            ax,ay=project(a);bx,by=project(b)
            body+=f'<path d="M{ax:.2f},{ay:.2f}L{bx:.2f},{by:.2f}" fill="none" stroke="#a95522" stroke-width="3" marker-end="url(#a)"/>'
        for label,point in marks:
            x,y=project(point)
            body+=f'<circle cx="{x:.2f}" cy="{y:.2f}" r="13" fill="#fff5d4" stroke="#8b4c22" stroke-width="2"/>'+svg_text(x,y+7,str(label),20,'middle')
        for i,label in enumerate(labels):body+=svg_text(18,452+i*28,label,20)
        body+=extra
        bottom=474+(len(labels)-1)*28 if labels else 430
        path=output/(name+'.svg')
        path.write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 50 420 {bottom-50}" role="img"><title>{html.escape(title)}</title><defs><marker id="a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#a95522"/></marker></defs><rect y="50" width="420" height="{bottom-50}" fill="#f3f7fa"/><g font-family="{font}">{body}</g></svg>')
        outputs.append('assets/community/'+path.name)

    # Feet: show only actual outer posts; the purchased foot size is not fixed.
    parts=chosen(['FB01'])
    emit('feet-posts',parts,[.7,-1.2,-1.2],'Stick one foot on each post',
         ['Post faces: Ø14 mm'],
         [(i+1,[x,y,-69]) for i,(x,y) in enumerate([(-95,-82.5),(95,-82.5),(-95,82.5),(95,82.5)])])
    # Purchased foot shown as an example shape, not a fixed stock dimension.
    foot=solid(trimesh.creation.cylinder(4,4,sections=64),'Rubber foot',[0,0,1],[95,-82.5,-79])
    foot_parts=cropped(chosen(['FB01']),[[84,-94,-70],[106,-71,-52]])+[foot]
    emit('foot-application',foot_parts,[.4,-1,-1],'Center the foot on the post',
         [],
         arrows=[([95,-82.5,-77],[95,-82.5,-69])])
    def illustrated_wago(y, lift=0):
        parts=[]
        def box(name,size,position):
            mesh=trimesh.creation.box(size);mesh.apply_translation(position)
            return dict(id=name,occ=0,root=name,v=mesh.vertices,f=mesh.faces,source={},flat_shading=True)
        parts.append(box('WAGO housing',[30,18.6,8.4],[48,y,-17.2-lift]))
        for x in [36,42,48,54,60]:
            parts.append(box('WAGO lever',[4.8,12,1.2],[x,y+1,-22-lift]))
            parts.append(solid(trimesh.creation.cylinder(1.15,.25,sections=32),'WAGO port',[0,1,0],[x,y-9.45,-17.5-lift]))
        if lift:parts.append(box('Tape',[29,17.6,.3],[48,y,-12.7-lift]))
        return parts
    parts=cropped(chosen(['FB01']),[[25,36,-17],[71,68,-2]])+illustrated_wago(52,12)
    emit('wago-tape-mount',parts,[.3,-.8,-1.4],'Tape the flat back to its pad',
         [],
         arrows=[([48,52,-25],[48,52,-13])])
    emit('wago-tape-back',illustrated_wago(52,12),[.3,-.8,1.4],'Put tape on the flat back',
         [])
    parts=chosen(['FB01'])
    for y in [52,22,-8,-38]:parts+=illustrated_wago(y)
    emit('wago-finished-layout',parts,[.12,.3,-1.8],'Four WAGOs, rear to front',
         ['1 = W1   2 = W3   3 = W2   4 = W4'],
         [(i+1,[48,y,-23]) for i,y in enumerate([52,22,-8,-38])])
    # Frame attachment, one actual section plus a loose nominal nut.
    parts=cropped(chosen(['FB01','P01','P02'],{'P01':[0],'P02':[0]}),[[-9,17,-7],[9,36,17]])
    parts+=[nut(3,[0,40,6.2],[0,0,1])]
    emit('frame-base-fastening',parts,[.8,1,.35],'Load each upright foot nut',
         [],
         arrows=[([0,37,6.2],[0,28,6.2])])
    # P14 and P08 are a bench assembly. The servo is deliberately absent.
    # The whole parts establish the three-hole orientation; the section below
    # separately reveals the underside nut pocket without hiding their shapes.
    shelf_positions=SHELF_FASTENING_CENTERS
    parts=chosen(['P08','P14'])
    for part in parts:part['guide_color']=(174,99,52) if part['id']=='P14' else (140,159,179)
    for x,y in shelf_positions:
        parts+=shelf_screw(np.array([x,y,140.3]))+[nut(3,[x,y,122.8],[0,0,1])]
    # Builders joined these upside down at the bench: mark the faces that stay up.
    emit('head-shelf-fastening',parts,[.6,-1.2,1.1],'Join shelf P08 to adapter P14',
         ['1 P14 flange, on top','2 Head nut pockets, on top','3 × M3 × 8 · brown: P14 · blue-gray: P08'],
         [('1',[4,-20,132]),('2',[33,0,130])],
         arrows=[([x,y,137],[x,y,129]) for x,y in shelf_positions])
    parts=cropped(chosen(['P08','P14']),[[0,12,120],[5,24,130]])
    for part in parts:part['guide_color']=(174,99,52) if part['id']=='P14' else (140,159,179)
    parts+=shelf_screw(np.array([0,18,140.3]))+[nut(3,[0,18,122.8],[0,0,1])]
    emit('head-shelf-joint-section',parts,[-1,.6,.3],'Join shelf P08 to adapter P14',
         ['M3 × 8 · brown: P14 · blue-gray: P08'],
         arrows=[([0,18,137],[0,18,129])])
    # The original measured disk is shown in a face diagram separately; here
    # the actual adapter shows both offset holes and its central servo opening.
    parts=chosen(['P14'])+[round_horn([0,0,107])]
    for x in [-9,9]:parts+=screw(2,6,[x,0,98],[0,0,1])+[nut(2,[x,0,122],[0,0,1])]
    emit('head-horn-offset-holes',parts,[.5,-1,-1],'Fasten the horn to P14 first',
         ['1 M2 × 6 screws · 2 Center hole, left open'],
         [('1',[-9,0,98]),('1',[9,0,98]),('2',[0,0,107])],arrows=[([0,0,108],[0,0,116])])
    parts=chosen(['P08'])+tube([[-12,-24,101],[-10,-26,110],[-10,-26,123],[-10,-26,133],[-12,-28,140],[-18,-31,143],[-25,-33,140],[-28,-32,133]],1.2)
    emit('head-cable-entry',parts,[-.8,-1,1.3],'Lay in the head light cable',
         ['1 Head light cable'],
         [('1',[-10,-26,123])],arrows=[([-27,-26,124],[-12,-26,124])])
    parts=cropped(chosen(['P08']),[[-22,-34,121.3],[0,-17,125.4]])
    parts+=tube([[-10,-26,115],[-10,-26,123],[-10,-26,133]],1.2)
    emit('head-cable-entry-detail',parts,[-.8,-1,1.3],'Place the cable through the side slot',
         [],
         arrows=[([-24,-26,123],[-12,-26,123])])
    # Mouth board screws are the inner pair; clamp screws are the outer pair.
    parts=translated(chosen(['P30','E04']),{'E04':[0,-10,0]})
    for x in [-12.7,12.7]:parts+=screw(2,8,[x,-36,136.65],[0,1,0])+[nut(2,[x,-12.5,136.65],[0,1,0])]
    emit('mouth-board-fastening',parts,[.5,-1.5,.6],'Fasten the LED stick to P30',
         ['1 Inner holes: 2 × M2 × 8 + nuts'],
         [('1',[-12.7,-36,136.65]),('1',[12.7,-36,136.65])],arrows=[([0,-28,136.65],[0,-16,136.65])])
    parts=chosen(['P30','P31','MOUTHFOAM'])
    for x in [-28.3,28.3]:parts+=screw(2,8,[x,-8,129.53],[0,-1,0])
    emit('mouth-clamp-fastening',parts,[.5,1.6,.4],'Clamp the mouth inside the head',
         ['1 Outer holes: 2 × M2 × 8'],
         [('1',[-28.3,-8,129.53]),('1',[28.3,-8,129.53])])
    parts=cropped(chosen(['GS20']),[[-55,-48,121],[55,35,144]])
    emit('mouth-head-nuts',parts,[.4,1.5,-.4],'Load the two hidden head nuts',
         ['1 M2 nuts'],
         [('1',[-28.3,-22,129.53]),('1',[28.3,-22,129.53])])
    parts=translated(chosen(['P30','E04']),{'P30':[0,8,0],'E04':[0,8,0]})
    for part in parts:part['guide_color']=(175,102,61)
    fixed=chosen(['P31','MOUTHFOAM'])+cropped(chosen(['GS20']),[[-60,-60,121.3],[60,60,128]])
    for part in fixed:part['guide_color']=(207,216,224)
    parts+=fixed
    emit('mouth-removal',parts,[1.4,.9,.75],'Remove the mouth cassette',
         ['Copper: mouth cassette'],
         arrows=[([0,-9,144],[0,-1,144]),([0,-1,144],[0,-1,116])])
    # Upright pockets remain accessible until the foam is wrapped.
    parts=chosen(['P02'],{'P02':[0]})
    emit('rear-seam-nuts',parts,[.8,1,.1],'Load the rear seam nuts first',
         ['M3 nuts: 1 middle slot · 2 upper slot'],
         [('1',[0,27,46]),('2',[0,27,90])],bounds=[[-12,16,34],[12,36,102]])
    parts=chosen(['P34','P02','P09','P10','P12'],{'P02':[0]})
    for xx in [-23,23]:
        for zz in [40,80]:parts.append(nut(3,[xx,41.4,zz],[0,1,0]))
    emit('carrier-side-nuts',parts,[.9,1,.25],'Load all four carrier nuts',
         ['1–4 M3 nuts'],
         [(i+1,[x,41.4,z]) for i,(x,z) in enumerate([(-23,40),(23,40),(-23,80),(23,80)])],
         arrows=[([x,41.4,z],[12 if x>0 else -12,41.4,z]) for x in [-23,23] for z in [40,80]])
    parts=translated(chosen(['P02','P09','P10','P12','P34'],{'P02':[0]}),{'P34':[0,18,0]})
    for z in [46,90]:parts+=screw(3,18,[0,76,z],[0,-1,0])
    emit('carrier-frame-fastening',parts,[.9,1,.25],'Fasten the carrier to the frame',
         ['1, 2 M3 × 18'],
         [('1',[0,76,46]),('2',[0,76,90])],bounds=[[-25,19,26],[25,80,101]],arrows=[([0,61,66],[0,43,66])])
    parts=translated(chosen(['P34','P35','P36','P37','P38','P39','P40']),{pid:[0,18,0] for pid in ['P35','P36','P37','P38','P39','P40']})
    for x in [-12,12]:
        for z in [40,80]:parts+=screw(3,12,[x,82,z],[0,-1,0])
    emit('backpack-shell-fastening',parts,[.7,1,.4],'Attach the completed backpack',
         ['1–4 M3 × 12'],
         [(i+1,[x,82,z]) for i,(x,z) in enumerate([(-12,40),(12,40),(-12,80),(12,80)])],arrows=[([0,64,67],[0,44,67])])
    # Highlight the bonded surfaces inside the two rings using source triangles;
    # no manufactured glue shape is invented.
    shell=chosen(['P35']);parts=[]
    for row in shell:
        triangles=row['v'][row['f']]
        ring=np.zeros(len(triangles),dtype=bool)
        band=((triangles[:,:,2]>=32.999)&(triangles[:,:,2]<=38.001))|((triangles[:,:,2]>=61.999)&(triangles[:,:,2]<=67.001))
        for x in (-28,28):
            radial=np.linalg.norm(triangles[:,:,:2]-[x,43],axis=2)
            ring|=(np.all(abs(radial-8.3)<.003,axis=1)&np.all(band,axis=1))
        parts+=[dict(row,f=row['f'][~ring],guide_color=(219,218,204)),
                dict(row,f=row['f'][ring],guide_color=(224,169,43),flat_shading=True)]
    tanks=chosen(['P36'])
    for row in tanks:
        # Separate along X only for a clear view of the hidden surfaces.
        row['v']=row['v']+[24 if row['v'][:,0].mean()>0 else -24,0,0]
        row['guide_color']=(174,99,52)
    parts+=tanks
    emit('tank-ring-bond',parts,[.5,1,.85],'Bond the tanks inside both rings',
         ['1, 2 Rings · gold: contact surfaces'],
         marks=[('1',[28,43,35.5]),('2',[28,43,64.5])])
    # P11 light pads and actual tie slots. No fixed tie-lock position implied.
    parts=cropped(chosen(['P11'],{'P11':[0]}),[[9,-36,8],[26,-16,36]])
    # Recognizable resin/LED/wire illustration on the accepted pad. Geometry
    # dimensions are nominal reference bounds; tie routing is illustrative.
    resin=trimesh.creation.icosphere(subdivisions=3,radius=1)
    resin.vertices*=np.array([2.5,1.685,6.]);resin.apply_translation([17.5,-21.935,22])
    parts.append(dict(id='Pebble resin',occ=0,root='Pebble illustration',v=resin.vertices,f=resin.faces,source={}))
    led=trimesh.creation.box([2.6,.3,3.0]);led.apply_translation([17.5,-23.8,22])
    parts.append(dict(id='LED face',occ=0,root='LED face',v=led.vertices,f=led.faces,source={},flat_shading=True))
    parts+=tube([[17.5,-21.9,9],[17.5,-21.9,16]],.48,'Wire')+tube([[17.5,-21.9,28],[17.5,-21.9,35]],.48,'Wire')
    for zz in [14.5,29.5]:
        parts+=tube([[11.8,-17.1,zz],[11.8,-23,zz],[23.2,-23,zz],[23.2,-17.1,zz],[11.8,-17.1,zz]],.75,'Tie')
    emit('pebble-wire-restraint',parts,[.3,-1.4,.4],'Tie the wires, not the light',
         ['1, 2 Cable ties'],
         [('1',[17.5,-23,14.5]),('2',[17.5,-23,29.5])],bounds=[[8,-36,8],[27,-15,36]])
    parts=chosen(['P04','P14','P08','E01'],{'E01':[2]})
    emit('head-center-screw',parts,[.6,-1,1.3],'Seat the head horn at the fit position',
         ['1 Center screw'],
         [('1',[0,0,128])],arrows=[([0,0,153],[0,0,130])])
    for suffix,arm,occ,sign in [('left','AR01',0,1),('right','AR04',1,-1)]:
        parts=chosen([arm,'E01'],{'E01':[occ]})
        emit('arm-center-screw-'+suffix,parts,[sign*1.8,-.6,.6],f'Seat the {suffix} arm at its fit position',
             ['1 Center screw'],
             [('1',[sign*48,0,90])],arrows=[([sign*65,0,90],[sign*48,0,90])])
    # The actual upper-arm/horn bore stays visible before its cover slides on.
    for suffix,arm,cover,sign in [('left','AR01','AR08',1),('right','AR04','AR09',-1)]:
        parts=translated(chosen([arm,cover]),{cover:[sign*18,0,0]})
        emit('shoulder-cover-'+suffix,parts,[sign*1.7,-1,.5],f'Fit the {suffix} shoulder cover',
             [f'{cover} on {arm}'],
             arrows=[([sign*66,0,86],[sign*48,0,86])])
    render.meshes=original
    return outputs

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path,required=True)
    parser.add_argument('--font',type=Path,default=Path('/System/Library/Fonts/Supplemental/Arial.ttf'))
    parser.add_argument('--write',action='store_true')
    mode=parser.add_mutually_exclusive_group()
    mode.add_argument('--front-only',action='store_true')
    mode.add_argument('--audio-only',action='store_true')
    mode.add_argument('--inlet-only',action='store_true')
    mode.add_argument('--boards-only',action='store_true')
    mode.add_argument('--context-only',action='store_true')
    mode.add_argument('--joint-actions-only',action='store_true')
    mode.add_argument('--legacy-only',action='store_true')
    mode.add_argument('--mount-closeups-only',action='store_true')
    mode.add_argument('--actions-only',action='store_true')
    mode.add_argument('--closeups-only',action='store_true')
    mode.add_argument('--body-only',action='store_true')
    mode.add_argument('--scene',action='append',help='Render only this existing asset path; repeat for several')
    args=parser.parse_args();args.output.mkdir(parents=True,exist_ok=False)
    source,registry,registry_hash=checked_source()
    os.environ.update(BGB_RENDER_OUTPUT=str(args.output.resolve()),BGB_RENDER_FONT=str(args.font.resolve()),BGB_RENDER_MESH_SOURCE=str(source))
    sys.path.insert(0,str(ROOT/'hardware/tools/rendering'));render=importlib.import_module('render')
    verify_reference_identities(render.meshes)
    from guide_component_models import replace_envelopes
    render.meshes=replace_envelopes(render.meshes)
    for row in json.loads((ROOT/'hardware/rendering/source-lock.json').read_text())['files']:
        if row['path'] in ('hardware/rendering/r22-colors.json','hardware/rendering/scenes/views.json') and digest(ROOT/row['path']) != row['sha256']:
            raise ValueError('Changed scene/palette input: '+row['path'])
    palette={(r['path'],r['body']):r['chosen_rgb'] for r in json.loads((ROOT/'hardware/rendering/r22-colors.json').read_text())['assignments']}
    base=render.col;lighten=True
    def color(m,highlight):
        if 'guide_color' in m:return m['guide_color']
        if m['id'] in ('M3 screw','M3 nut'):return render.colors[m['id']]
        if m['id'] in ('Cable','Wire'):return (58,112,180)
        if m['id']=='Tie':return (183,103,53)
        if m['id']=='Pebble resin':return (223,226,221)
        if m['id']=='LED face':return (244,206,87)
        if m['id']=='Horn outline':return (222,219,199)
        if m['id'] in ('Rubber foot','WAGO port'):return (45,49,54)
        if m['id']=='WAGO housing':return (221,229,233)
        if m['id']=='WAGO lever':return (228,118,36)
        if m['id']=='Tape':return (181,98,61)
        if m['id'] in ('J01','J02','J04'):return (188,145,91)
        if m['id']=='J05':return (94,116,184)
        if m['id'] in ('J03','J06'):return (57,62,70)
        if lighten and m['id']=='FB01':return (180,191,202)
        return tuple(palette.get((m['source'].get('path'),m['source'].get('body'))) or base(m,highlight))
    render.col=color
    from render_hand_arm_actions import ACTION_PATHS, make_images
    outputs={}
    if not args.body_only and (not args.legacy_only and not args.joint_actions_only and not args.context_only and not args.boards_only and not args.inlet_only and not args.audio_only and not args.front_only and not args.actions_only and not args.closeups_only and not args.mount_closeups_only):
        selected=scenes()
        if args.scene:
            unknown=set(args.scene)-selected.keys()-ACTION_PATHS
            if unknown:raise ValueError('Unknown selected scenes: '+', '.join(sorted(unknown)))
            selected={p:v for p,v in selected.items() if p in args.scene}
        for index,(path,scene) in enumerate(selected.items()):
            scene=dict(scene,view=dict(scene['view'],guide=True))
            lighten='main-front' not in path and 'overview-back' not in path
            name='scene-'+str(index)
            if path in ('assets/r21/base-frame.png','assets/r21/base-cover.png'):
                from guide_closeups import pose_parts
                import numpy as np
                rotation=np.array([[0,0,1],[0,1,0],[-1,0,0]]) if 'base-frame' in path else np.array([[1,0,0],[0,0,1],[0,-1,0]])
                original=render.meshes;render.meshes=pose_parts(original,rotation)
                view=copy.deepcopy(scene['view'])
                camera=[-.8,-1,-.65] if 'base-frame' in path else view['camera']
                view['camera']=(rotation@camera).tolist()
                view['offset']={pid:(rotation@offset).tolist() for pid,offset in view.get('offset',{}).items()}
                render.render(name,view,scene['thumbnail']);render.meshes=original
            elif path == 'assets/r16/base-button.png':
                from guide_component_actions import button_leads
                original=render.meshes;render.meshes=original+button_leads(original)
                render.render(name,scene['view'],scene['thumbnail']);render.meshes=original
            else:
                render.render(name,scene['view'],scene['thumbnail'])
            outputs[path]=args.output/(name+'.png')
            print('Rendered',path,flush=True)
    lighten=True
    if not args.body_only and (not args.legacy_only and not args.joint_actions_only and not args.context_only and not args.boards_only and not args.inlet_only and not args.audio_only and not args.actions_only and not args.closeups_only and not args.scene):
        for path in front_diagrams(render,args.output):outputs[path]=args.output/Path(path).name
    if not args.body_only and (not args.legacy_only and not args.joint_actions_only and not args.context_only and not args.boards_only and not args.inlet_only and not args.audio_only and not args.front_only and not args.closeups_only and not args.scene and not args.mount_closeups_only):
        for path in action_diagrams(render,args.output):outputs[path]=args.output/Path(path).name
    if not args.body_only and (not args.legacy_only and not args.joint_actions_only and not args.context_only and not args.boards_only and not args.inlet_only and not args.audio_only and not args.front_only and not args.actions_only and not args.closeups_only and not args.scene):
        for path in base_nut_diagrams(render,args.output):outputs[path]=args.output/Path(path).name
    if not args.body_only and (args.closeups_only or not (args.legacy_only or args.joint_actions_only or args.context_only or args.boards_only or args.inlet_only or args.audio_only or args.front_only or args.actions_only or args.scene or args.mount_closeups_only)):
        from guide_closeups import render_closeups
        for path in render_closeups(render,args.output):outputs[path]=args.output/Path(path).name
    if not args.body_only and (args.audio_only or not (args.legacy_only or args.joint_actions_only or args.context_only or args.boards_only or args.inlet_only or args.front_only or args.actions_only or args.closeups_only or args.scene or args.mount_closeups_only)):
        from guide_closeups import render_audio_closeups
        for path in render_audio_closeups(render,args.output):outputs[path]=args.output/Path(path).name
    if not args.body_only and (args.inlet_only or not (args.legacy_only or args.joint_actions_only or args.context_only or args.boards_only or args.audio_only or args.front_only or args.actions_only or args.closeups_only or args.scene or args.mount_closeups_only)):
        from guide_closeups import render_inlet_closeups
        for path in render_inlet_closeups(render,args.output):outputs[path]=args.output/Path(path).name
    if not args.body_only and (args.boards_only or not (args.legacy_only or args.joint_actions_only or args.context_only or args.inlet_only or args.audio_only or args.front_only or args.actions_only or args.closeups_only or args.scene or args.mount_closeups_only)):
        from guide_closeups import render_board_closeups
        for path in render_board_closeups(render,args.output):outputs[path]=args.output/Path(path).name
        from guide_layout import render_layout
        for path in render_layout(render,args.output):outputs[path]=args.output/Path(path).name
    if not args.body_only and (args.context_only or not (args.legacy_only or args.joint_actions_only or args.boards_only or args.inlet_only or args.audio_only or args.front_only or args.actions_only or args.closeups_only or args.scene or args.mount_closeups_only)):
        from guide_context_actions import render_context_actions
        for path in render_context_actions(render,args.output):outputs[path]=args.output/Path(path).name
    if not args.body_only and (args.joint_actions_only or not (args.legacy_only or args.context_only or args.boards_only or args.inlet_only or args.audio_only or args.front_only or args.actions_only or args.closeups_only or args.scene or args.mount_closeups_only)):
        from guide_joint_actions import render_joint_actions
        for path in render_joint_actions(render,args.output):outputs[path]=args.output/Path(path).name
    if not args.body_only and (args.legacy_only or not (args.joint_actions_only or args.context_only or args.boards_only or args.inlet_only or args.audio_only or args.front_only or args.actions_only or args.closeups_only or args.scene or args.mount_closeups_only)):
        from guide_legacy_actions import render_legacy_actions
        for path in render_legacy_actions(render,args.output):outputs[path]=args.output/Path(path).name
    if args.body_only or not (args.legacy_only or args.joint_actions_only or args.context_only or args.boards_only or args.inlet_only or args.audio_only or args.front_only or args.actions_only or args.closeups_only or args.scene or args.mount_closeups_only):
        from guide_closeups import render_body_closeups
        for path in render_body_closeups(render,args.output):outputs[path]=args.output/Path(path).name
    # Action drawings supersede the plain model views at these same public paths.
    # Apply only selected outputs, so a focused board render cannot change wrists.
    hand_action_witnesses = None
    selected_actions = (set(outputs) | set(args.scene or [])) & ACTION_PATHS
    if selected_actions:
        corrected, hand_action_witnesses = make_images(render, args.output, args.font)
        outputs.update({path: corrected[path] for path in selected_actions})
    if digest(ROOT/'hardware/cad/design-control/registry.json')!=registry_hash:
        raise ValueError('Registry changed during rendering; inspect before applying images')
    if args.write:
        for path,temporary in outputs.items():
            if (SRC/path).is_file():shutil.copyfile(temporary,SRC/path)
    receipt=dict(generator_sha256=digest(Path(__file__)), renderer_sha256=digest(ROOT/'hardware/tools/rendering/render.py'), native_occurrences_verified=['FB01 Structural base:1','FB24 Audio cradle - captive lid nuts:1','FB41 Microphone grille reused:1'], cad=registry['main'],mesh_source=str(source.relative_to(ROOT)),mesh_sha256=digest(source),registry_sha256=registry_hash,source_lock_sha256=digest(ROOT/'hardware/rendering/source-lock.json'),font_sha256=digest(args.font),outputs={p:digest(v) for p,v in outputs.items()},scenes=render.render_audit)
    if args.boards_only or args.inlet_only or args.audio_only or args.closeups_only or not (args.legacy_only or args.joint_actions_only or args.context_only or args.front_only or args.actions_only or args.scene or args.mount_closeups_only):
        receipt['closeups_helper_sha256']=digest(ROOT/'hardware/tools/rendering/guide_closeups.py')
    if args.context_only or not (args.legacy_only or args.joint_actions_only or args.boards_only or args.inlet_only or args.audio_only or args.front_only or args.actions_only or args.closeups_only or args.scene or args.mount_closeups_only):
        receipt['context_helper_sha256']=digest(ROOT/'hardware/tools/rendering/guide_context_actions.py')
        receipt['closeups_helper_sha256']=digest(ROOT/'hardware/tools/rendering/guide_closeups.py')
    if args.joint_actions_only or not (args.legacy_only or args.context_only or args.boards_only or args.inlet_only or args.audio_only or args.front_only or args.actions_only or args.closeups_only or args.scene or args.mount_closeups_only):
        receipt['joint_helper_sha256']=digest(ROOT/'hardware/tools/rendering/guide_joint_actions.py')
        receipt['closeups_helper_sha256']=digest(ROOT/'hardware/tools/rendering/guide_closeups.py')
    receipt['speaker_helper_sha256']=digest(ROOT/'hardware/tools/rendering/guide_speaker_actions.py')
    receipt['component_helper_sha256']=digest(ROOT/'hardware/tools/rendering/guide_component_models.py')
    receipt['component_actions_sha256']=digest(ROOT/'hardware/tools/rendering/guide_component_actions.py')
    receipt['routing_helper_sha256']=digest(ROOT/'hardware/tools/rendering/guide_routing.py')
    receipt['routing_data_sha256']=digest(ROOT/'hardware/rendering/guide-routes.json')
    receipt['layout_helper_sha256']=digest(ROOT/'hardware/tools/rendering/guide_layout.py')
    receipt['fastener_helper_sha256']=digest(ROOT/'hardware/tools/rendering/guide_fasteners.py')
    receipt['legacy_helper_sha256']=digest(ROOT/'hardware/tools/rendering/guide_legacy_actions.py')
    if hand_action_witnesses is not None:
        receipt['hand_arm_helper_sha256'] = digest(ROOT/'hardware/tools/guide/render_hand_arm_actions.py')
        receipt['hand_arm_geometry_witnesses'] = hand_action_witnesses
    (args.output/'render-receipt.json').write_text(json.dumps(receipt,indent=2)+'\n')
    print('Rendered',len(outputs),'authored images; applied:',args.write)

if __name__=='__main__':main()
