"""Persist the standard Pi OS Netplan Wi-Fi profile as a native NM keyfile.

Raspberry Pi documents that non-netplan keyfiles bypass its YAML regeneration:
https://www.raspberrypi.com/news/cloud-init-on-raspberry-pi-os/
Only the single active Wi-Fi layout generated by Imager is migrated. Preserve
all connection settings; never restart networking or apply/activate a profile.
"""

from __future__ import annotations

import configparser
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
from uuid import UUID

RUNTIME = Path("/run/NetworkManager/system-connections")
PERSISTENT = Path("/etc/NetworkManager/system-connections")
NETPLAN = Path("/etc/netplan")
BACKUPS = Path("/var/lib/blooglyblob-wifi-backup")


def command(*args: str) -> str:
    try:
        return subprocess.run(
            args, check=True, text=True, capture_output=True, timeout=30
        ).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        # NM and YAML diagnostics may include SSIDs or credentials.
        raise RuntimeError(
            "Wi-Fi persistence command failed; networking was not restarted"
        ) from None


def read(path: Path) -> bytes:
    if path.is_symlink() or not path.is_file():
        raise RuntimeError("Wi-Fi persistence requires regular profile files")
    return path.read_bytes()


def profile(data: bytes) -> configparser.ConfigParser:
    parsed = configparser.ConfigParser(interpolation=None)
    try:
        parsed.read_string(data.decode())
    except (UnicodeError, configparser.Error):
        raise RuntimeError("Wi-Fi profile could not be parsed") from None
    return parsed


def sync_directory(path: Path) -> None:
    fd = os.open(path, os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def write_private(path: Path, data: bytes) -> None:
    fd, temporary = tempfile.mkstemp(prefix=".wifi-", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
        sync_directory(path.parent)
    finally:
        Path(temporary).unlink(missing_ok=True)


def validate_yaml(path: Path, uuid: str) -> None:
    # Use the system's python3-yaml (installed with provisioning), without adding
    # a YAML dependency to the application or bootstrap imports. Capture output.
    data = json.loads(
        command(
            "/usr/bin/python3",
            "-c",
            "import json,sys,yaml; print(json.dumps(yaml.safe_load(open(sys.argv[1]))))",
            str(path),
        )
    )
    if not isinstance(data, dict) or set(data) != {"network"}:
        raise RuntimeError("Wi-Fi Netplan file has an unsupported layout")
    network = data["network"]
    if not isinstance(network, dict) or set(network) - {"version", "renderer", "wifis"}:
        raise RuntimeError("Wi-Fi Netplan file also configures other interfaces")
    wifis = network.get("wifis", {})
    if not isinstance(wifis, dict) or len(wifis) != 1:
        raise RuntimeError("Wi-Fi migration requires one Netplan Wi-Fi profile")
    node = next(iter(wifis.values()))
    if not isinstance(node, dict):
        raise RuntimeError("Wi-Fi Netplan profile has an unsupported layout")
    if "regulatory-domain" in node:
        raise RuntimeError(
            "Wi-Fi country is managed by Netplan; inspect before migration"
        )
    aps = node.get("access-points", {})
    if not isinstance(aps, dict) or len(aps) != 1:
        raise RuntimeError("Wi-Fi migration requires one access point")
    ap = next(iter(aps.values()))
    if not isinstance(ap, dict):
        raise RuntimeError("Wi-Fi access point has an unsupported layout")
    ids = [
        block["networkmanager"]["uuid"]
        for block in (node, ap)
        if isinstance(block.get("networkmanager"), dict)
        and "uuid" in block["networkmanager"]
    ]
    if (
        not ids
        or any(value != uuid for value in ids)
        or node.get("renderer", network.get("renderer")) != "NetworkManager"
    ):
        raise RuntimeError("Wi-Fi Netplan identity does not match the active profile")


def backup(directory: Path, original: bytes, yaml: bytes) -> None:
    BACKUPS.mkdir(mode=0o700, exist_ok=True)
    if (
        BACKUPS.is_symlink()
        or BACKUPS.stat().st_mode & 0o077
        or BACKUPS.stat().st_uid != os.geteuid()
    ):
        raise RuntimeError("Wi-Fi backup directory must be private")
    if directory.exists():
        if (
            directory.is_symlink()
            or directory.stat().st_mode & 0o077
            or directory.stat().st_uid != os.geteuid()
            or read(directory / "profile.nmconnection") != original
            or read(directory / "netplan.yaml") != yaml
            or any(
                p.stat().st_mode & 0o077 or p.stat().st_uid != os.geteuid()
                for p in (
                    directory / "profile.nmconnection",
                    directory / "netplan.yaml",
                )
            )
        ):
            raise RuntimeError(
                "Wi-Fi backup differs; inspect before retrying provisioning"
            )
        return
    temporary = Path(tempfile.mkdtemp(prefix=".preparing-", dir=BACKUPS))
    try:
        write_private(temporary / "profile.nmconnection", original)
        write_private(temporary / "netplan.yaml", yaml)
        temporary.rename(directory)
        sync_directory(BACKUPS)
    finally:
        if temporary.exists():
            shutil.rmtree(temporary)


def configure() -> None:
    sources = sorted(RUNTIME.glob("netplan-*.nmconnection"))
    if not sources:
        print(
            "Wi-Fi persistence: no generated profile to migrate; existing settings unchanged."
        )
        return
    if len(sources) != 1:
        raise RuntimeError(
            "Wi-Fi migration requires the standard single-profile Imager setup"
        )
    source = sources[0]
    original = read(source)
    parsed = profile(original)
    if parsed.get("connection", "type", fallback="") not in {"wifi", "802-11-wireless"}:
        print(
            "Wi-Fi persistence: no generated Wi-Fi profile; existing settings unchanged."
        )
        return
    try:
        uuid = str(UUID(parsed.get("connection", "uuid")))
    except (ValueError, configparser.Error, AttributeError):
        raise RuntimeError("Wi-Fi profile has no valid connection UUID") from None
    active = command(
        "nmcli", "-g", "UUID", "connection", "show", "--active"
    ).splitlines()
    if uuid not in active:
        raise RuntimeError("Wi-Fi profile must be active before migration")
    if (
        not parsed.get("wifi-security", "psk", fallback="")
        or parsed.get("wifi-security", "psk-flags", fallback="0") != "0"
        or parsed.get("wifi-security", "key-mgmt", fallback="")
        not in {"wpa-psk", "sae"}
    ):
        raise RuntimeError("Wi-Fi migration requires a saved WPA personal password")
    # Keep keyfile escaping, static addresses, DNS, MAC choices and all other
    # settings byte-for-byte. Rename only this section's connection label.
    section = re.search(rb"(?ms)^\[connection\]\r?\n.*?(?=^\[|\Z)", original)
    if section is None:
        raise RuntimeError("Wi-Fi connection section missing")
    renamed, count = re.subn(
        rb"(?m)^id=[^\r\n]*", f"id=blooglyblob-wifi-{uuid}".encode(), section[0]
    )
    if count != 1:
        raise RuntimeError("Wi-Fi connection label is ambiguous")
    new = original[: section.start()] + renamed + original[section.end() :]
    destination = PERSISTENT / f"blooglyblob-wifi-{uuid}.nmconnection"
    saved = BACKUPS / uuid
    yaml = NETPLAN / f"90-NM-{uuid}.yaml"
    configs = set(NETPLAN.glob("*.yaml")) | set(NETPLAN.glob("*.yml"))
    if configs - {yaml}:
        raise RuntimeError(
            "Wi-Fi migration found additional Netplan files; settings unchanged"
        )
    # Resume if interrupted between retiring the YAML and its generated file.
    yaml_data = read(yaml) if yaml.exists() else read(saved / "netplan.yaml")
    validate_yaml(yaml if yaml.exists() else saved / "netplan.yaml", uuid)
    for existing in PERSISTENT.glob("*.nmconnection"):
        if existing == destination:
            if read(existing) != new:
                raise RuntimeError("Wi-Fi destination conflicts with existing settings")
        elif profile(read(existing)).get("connection", "uuid", fallback="") == uuid:
            raise RuntimeError("Wi-Fi UUID already has another persistent profile")
    backup(saved, original, yaml_data)
    write_private(destination, new)
    command("nmcli", "connection", "load", str(destination))
    loaded = command(
        "nmcli", "-t", "--escape", "no", "-f", "UUID,FILENAME", "connection", "show"
    ).splitlines()
    if (
        f"{uuid}:{destination}" not in loaded
        or uuid
        not in command(
            "nmcli", "-g", "UUID", "connection", "show", "--active"
        ).splitlines()
    ):
        raise RuntimeError(
            "Wi-Fi replacement did not verify; originals and backup retained"
        )
    # Refuse to retire originals if an external editor changed either meanwhile.
    if (
        read(source) != original
        or (yaml.exists() and read(yaml) != yaml_data)
        or read(destination) != new
    ):
        raise RuntimeError(
            "Wi-Fi settings changed during migration; inspect before retrying"
        )
    yaml.unlink(missing_ok=True)
    sync_directory(NETPLAN)
    source.unlink()
    sync_directory(RUNTIME)
    print(
        "Wi-Fi persistence configured; credentials unchanged and private backup retained. No network restart needed."
    )
